"""followers

Revision ID: 6757e0ea5db0
Revises: 7e4cd52f2aa6
Create Date: 2018-11-20 23:38:50.078863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6757e0ea5db0'
down_revision = '7e4cd52f2aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
